"use strict";

var countries = [];
var countryNamesAndCodes = [];

function read_csv_file_and_prepare_data() {

  function load_CSV_file() {
    var fs = require("fs");
    var data = fs.readFileSync(__dirname + "/GeoIPCountryWhois.csv")
    var buffer = "";
    buffer += data.toString();
    return buffer;
  }

  function extractPartsFromCsv(line) {
    var matches = line.match(/("(?:[^"]|"")*"|[^,]*)/g);
    var result = [];
    for (var i = 0; i < matches.length; i++) {
      var part = matches[i].replace(/"/g, "").trim();
      if (part.length > 0) {
        result.push(part);
      }
    }
    return result;
  }

  var entries = load_CSV_file().split("\n");
  var offsetCounter = 0;
  var countryIndex = 0;
  var countrySet = {};
  var lastIpRangeEnd = 0;

  for (var i = 0; i < entries.length; i++) {
    var parts = extractPartsFromCsv(entries[i]);
    if (parts.length > 5) {
      var countryName = parts[5].trim();
      var countryCode = parts[4];
      if (!countrySet[countryName]) {
        countryIndex = offsetCounter++;
        countrySet[countryName] = {index: countryIndex};
        countryNamesAndCodes.push(countryName);
        countryNamesAndCodes.push(countryCode);
      } else {
        countryIndex = countrySet[countryName].index;
      }
      countries.push(createCountryInformation(parseInt(parts[2]), parseInt(parts[3]), countryCode, countryName, (countryIndex * 2)));
      lastIpRangeEnd = parseInt(parts[3]);
    }
  }

  // add a special country, which indicates the END
  countryIndex = offsetCounter;
  countrySet["UNKNOWN"] = {index: countryIndex};
  countryNamesAndCodes.push("UNKNOWN");
  countryNamesAndCodes.push("N/A");
  countries.push(
     createCountryInformation(lastIpRangeEnd + 1, lastIpRangeEnd + 1, "N/A", "UNKNOWN", countryIndex * 2)
  );

  countries.sort(function (a, b) {
    return a.ipstart - b.ipstart;
  });

}

function createCountryInformation(ipStart, ipEnd, countryCode, countryName, index) {
  return {
    ipstart: ipStart,
    ipend: ipEnd,
    code: countryCode,
    name: countryName,
    index: index
  };
}


function write_sourceFile_countryNamesAndCodes() {
  var data = "";
  data += "// AUTOGENERATED CODE - DO NOT MODIFY!   " + new Date() + " \n";
  data += "var countryNamesAndCodes = [\n";
  for (var i = 0, len = countryNamesAndCodes.length >> 1; i < len; i++) {
    var countryName = countryNamesAndCodes[i << 1].replace("'", "\\'");
    var countryCode = countryNamesAndCodes[(i << 1) + 1].replace("'", "\\'");
    data += "'" + countryName + "','" + countryCode + "',\n";
  }
  data += "];\n";
  data += "module.exports = {\n";
  data += "   countryNamesAndCodes:countryNamesAndCodes\n";
  data += "};\n";

  var fs = require("fs");
  fs.writeFileSync('generated-namesandcodes.js', data, 'utf8');
}

function write_sourceFile_countries() {
  var data = "";
  data += "// AUTOGENERATED CODE - DO NOT MODIFY!   " + new Date() + " \n";
  data += "var countries = [\n";
  for (var i = 0, len = countries.length; i < len; i++) {
    var country = countries[i];
    data += "{s:" + country.ipstart + ",";
    data += "e:" + country.ipend + ",";
    data += "i:" + country.index + "},";
    data += "//" + countryNamesAndCodes[country.index + 1] + "\n";
  }
  data += "];\n";
  data += "module.exports = {\n";
  data += "   countries:countries\n";
  data += "};\n";

  var fs = require("fs");
  fs.writeFileSync('generated-countries.js', data, 'utf8');
}

/**
 * Prepare the data.  This uses the standard free GeoIP CSV database
 * from MaxMind, you should be able to update it at any time by just
 * overwriting GeoIPCountryWhois.csv with a new version.
 */

read_csv_file_and_prepare_data()
write_sourceFile_countryNamesAndCodes();
write_sourceFile_countries();
