var countries = [];
var countryNamesAndCodes = [];

function read_csv_file_and_prepare_data() {

   var fs = require("fs");
   var data = fs.readFileSync(__dirname + "/GeoIPCountryWhois.csv")
   var buffer = "";
   buffer += data.toString().replace(/"/g, "");

   var entries = buffer.split("\n");
   var offsetCounter = 0;
   var countrySet = {};

   for (var i = 0; i < entries.length; i++) {
      var entry = entries[i].split(",");
      if (entry.length > 5) {
         var countryName = entry[5].trim();
         var countryCode = entry[4];
         var countryIndex = 0;
         if (!countrySet[countryName]) {
            countryIndex = offsetCounter++;
            countrySet[countryName] = {index:countryIndex};
            countryNamesAndCodes.push(countryName);
            countryNamesAndCodes.push(countryCode);
         } else {
            countryIndex = countrySet[countryName].index;
         }
         countries.push({ipstart:parseInt(entry[2]), code:countryCode, name:countryName, index:(countryIndex * 2)});
      }
   }

   countries.sort(function (a, b) {
      return a.ipstart - b.ipstart;
   });

}

function write_sourceFile_countryNamesAndCodes() {
   var data = "";
   data += "// AUTOGENERATED CODE - DO NOT MODIFY!   " + new Date() + " \n";
   data += "var countryNamesAndCodes = [\n";
   for (var i = 0, len = countryNamesAndCodes.length >> 1; i < len; i++) {
      var countryName = countryNamesAndCodes[i<<1].replace("'", "\\'");
      var countryCode = countryNamesAndCodes[(i<<1)+1].replace("'", "\\'");
      data += "'" + countryName + "','"+countryCode+"',\n";
      data += "'" + countryName + "','"+countryCode+"',\n";
   }
   data += "];\n";
   data += "module.exports = {\n";
   data += "   countryNamesAndCodes:countryNamesAndCodes\n";
   data += "};\n";

   var fs = require("fs");
   fs.writeFileSync('generated-namesandcodes.js', data, 'utf8');
}

function write_sourceFile_countries() {
   var data = "";
   data += "// AUTOGENERATED CODE - DO NOT MODIFY!   " + new Date() + " \n";
   data += "var countries = [\n";
   for (var i = 0, len = countries.length; i < len; i++) {
      var country = countries[i];
      data += "{ipstart:" + country.ipstart + ",idx:" + country.index + "},//" + countryNamesAndCodes[country.index + 1] + "\n";
   }
   data += "];\n";
   data += "module.exports = {\n";
   data += "   countries:countries\n";
   data += "};\n";

   var fs = require("fs");
   fs.writeFileSync('generated-countries.js', data, 'utf8');
}

/**
 * Prepare the data.  This uses the standard free GeoIP CSV database
 * from MaxMind, you should be able to update it at any time by just
 * overwriting GeoIPCountryWhois.csv with a new version.
 */

read_csv_file_and_prepare_data()
write_sourceFile_countryNamesAndCodes();
write_sourceFile_countries();
